==3878== Memcheck, a memory error detector
==3878== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3878== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==3878== Command: ./cub3D own_test.cub
==3878== 
==3878== 
==3878== HEAP SUMMARY:
==3878==     in use at exit: 46,956,206 bytes in 2,764 blocks
==3878==   total heap usage: 69,094 allocs, 66,330 frees, 261,384,028 bytes allocated
==3878== 
==3878== 24 bytes in 1 blocks are definitely lost in loss record 70 of 2,030
==3878==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==3878==    by 0x1135F1: mlx_load_png (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x10BAB3: init_mlx (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x10BC71: init_data (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x10A62B: main (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878== 
==3878== 64 bytes in 1 blocks are definitely lost in loss record 1,858 of 2,030
==3878==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3878==    by 0x6B2E879: ???
==3878==    by 0x63F37DF: ???
==3878==    by 0x400FFE1: call_init.part.0 (dl-init.c:72)
==3878==    by 0x40100E8: call_init (dl-init.c:30)
==3878==    by 0x40100E8: _dl_init (dl-init.c:119)
==3878==    by 0x4B67AEC: _dl_catch_exception (dl-error-skeleton.c:182)
==3878==    by 0x4014363: dl_open_worker (dl-open.c:758)
==3878==    by 0x4B67A8F: _dl_catch_exception (dl-error-skeleton.c:208)
==3878==    by 0x40138F9: _dl_open (dl-open.c:837)
==3878==    by 0x4A0A257: dlopen_doit (dlopen.c:66)
==3878==    by 0x4B67A8F: _dl_catch_exception (dl-error-skeleton.c:208)
==3878==    by 0x4B67B4E: _dl_catch_error (dl-error-skeleton.c:227)
==3878== 
==3878== 5,355 bytes in 255 blocks are definitely lost in loss record 2,021 of 2,030
==3878==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==3878==    by 0x4ABBF3A: strdup (strdup.c:42)
==3878==    by 0x60144A6: ???
==3878==    by 0x6014254: ???
==3878==    by 0x5FB7F73: ???
==3878==    by 0x5EDB436: ???
==3878==    by 0x5EDBCE8: ???
==3878==    by 0x5F570F0: ???
==3878==    by 0x5F58417: ???
==3878==    by 0x4876D02: ??? (in /usr/lib/x86_64-linux-gnu/libglfw.so.3.3)
==3878==    by 0x4866477: ??? (in /usr/lib/x86_64-linux-gnu/libglfw.so.3.3)
==3878==    by 0x486BB6A: glfwCreateWindow (in /usr/lib/x86_64-linux-gnu/libglfw.so.3.3)
==3878== 
==3878== 160,000 bytes in 1 blocks are possibly lost in loss record 2,028 of 2,030
==3878==    at 0x483AB65: calloc (vg_replace_malloc.c:760)
==3878==    by 0x11A94E: decodeGeneric (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x11F4D9: lodepng_decode_memory (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x11FE23: lodepng_decode32_file (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x113610: mlx_load_png (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x10BAB3: init_mlx (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x10BC71: init_data (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878==    by 0x10A62B: main (in /home/pythongermany/vboxshare/42projects/42_cub3d/cub3D)
==3878== 
==3878== LEAK SUMMARY:
==3878==    definitely lost: 5,443 bytes in 257 blocks
==3878==    indirectly lost: 0 bytes in 0 blocks
==3878==      possibly lost: 160,000 bytes in 1 blocks
==3878==    still reachable: 46,790,731 bytes in 2,505 blocks
==3878==         suppressed: 32 bytes in 1 blocks
==3878== Reachable blocks (those to which a pointer was found) are not shown.
==3878== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==3878== 
==3878== For lists of detected and suppressed errors, rerun with: -s
==3878== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
